@baseUrl = http://localhost:3000
@authToken = {{authenticate.response.body.access_token}}
@productId = {{create_product.response.body.product.id}}

# @name create-user
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "Max Doe",
    "username": "max",
    "email": "max@doe.com",
    "password": "password"
}

###

# @name authenticate

POST {{baseUrl}}/auth
Content-Type: application/json

{
  "username": "max",
  "password": "password"
}

###

# @name create_product

POST {{baseUrl}}/products
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Product 1",
    "quantity": 4,
    "value": 10.99
}

###

# @name delete_product

DELETE {{baseUrl}}/products/{{productId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name edit_product

PUT {{baseUrl}}/products/{{productId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Product 2",
    "quantity": 5,
    "value": 10.99
}

###

# @name fetch_products

GET {{baseUrl}}/products
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_product_by_id

GET {{baseUrl}}/products/{{productId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}