@baseUrl = http://localhost:3000
@authToken = {{authenticate.response.body.access_token}}
@productId = {{create_product.response.body.product.id}}
@userId = {{get_user_by_username.response.body.user.id}}

# @name create_user
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "Max Doe",
    "username": "mfdasfax",
    "email": "max@dofade.com",
    "password": "password"
}

###

# @name authenticate

POST {{baseUrl}}/auth
Content-Type: application/json

{
  "username": "max",
  "password": "password"
}

###

# @name create_product

POST {{baseUrl}}/products
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Product 1",
    "quantity": 4,
    "value": 10.99
}

###

# @name delete_product

DELETE {{baseUrl}}/products/{{productId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name edit_product

PUT {{baseUrl}}/products/{{productId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Product 2",
    "quantity": 5,
    "value": 10.99
}

###

# @name fetch_products

GET {{baseUrl}}/products?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_product_by_id

GET {{baseUrl}}/products/{{productId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name fetch_users

GET {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_user_by_username

GET {{baseUrl}}/users/max
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_user_by_id

GET {{baseUrl}}/user/{{userId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name edit_user

PUT {{baseUrl}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Novo Nome",
    "email": "novo@email.com",
    "password": "5876489465841",
    "username": "novousername"
}

###

# @name delete_user

DELETE {{baseUrl}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}