@baseUrl = http://localhost:3000
@authToken = {{authenticate.response.body.access_token}}

# @name create-user
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "John Doe",
    "username": "johndoezera",
    "email": "john@doe.com",
    "password": "password"
}

###

# @name authenticate

POST {{baseUrl}}/auth
Content-Type: application/json

{
  "username": "johndoezera",
  "password": "password"
}